using Microsoft.AspNetCore.Mvc;
using ObserverPattern.Api.Models;
using ObserverPattern.Api.Observers;
using ObserverPattern.Api.Subject;

namespace ObserverPattern.Api.Controllers;

/// <summary>
/// REST façade for the Observer Pattern demo.
/// Allows clients to subscribe observers, publish price updates and query alerts.
/// </summary>
[ApiController]
[Route("api/stocks")]
public class StocksController(IStockMarket market, IEnumerable<IStockObserver> observers) : ControllerBase
{
    // ── Subscriptions ─────────────────────────────────────────────────────────

    /// <summary>
    /// Subscribe a named observer type to a stock symbol.
    /// Available observer types: EmailAlert, SmsAlert, Dashboard, AuditLog.
    /// </summary>
    [HttpPost("subscribe")]
    public IActionResult Subscribe([FromBody] SubscribeRequest req)
    {
        var observer = ResolveObserver(req.ObserverType);
        if (observer is null)
            return BadRequest(new { error = $"Unknown observer type '{req.ObserverType}'. " +
                "Valid values: EmailAlert, SmsAlert, Dashboard, AuditLog." });

        market.Subscribe(req.Symbol, observer);
        return Ok(new { message = $"{observer.Name} subscribed to {req.Symbol.ToUpperInvariant()}." });
    }

    /// <summary>
    /// Unsubscribe a named observer from a stock symbol.
    /// </summary>
    [HttpDelete("subscribe")]
    public IActionResult Unsubscribe([FromBody] SubscribeRequest req)
    {
        var observer = ResolveObserver(req.ObserverType);
        if (observer is null)
            return BadRequest(new { error = $"Unknown observer type '{req.ObserverType}'." });

        market.Unsubscribe(req.Symbol, observer);
        return Ok(new { message = $"{observer.Name} unsubscribed from {req.Symbol.ToUpperInvariant()}." });
    }

    // ── Price updates ─────────────────────────────────────────────────────────

    /// <summary>
    /// Publish a new price for a symbol — all subscribed observers are notified concurrently.
    /// </summary>
    [HttpPost("price")]
    public async Task<IActionResult> UpdatePrice([FromBody] UpdatePriceRequest req)
    {
        if (req.Price <= 0)
            return BadRequest(new { error = "Price must be greater than zero." });

        await market.UpdatePriceAsync(req.Symbol, req.Price);

        var history = market.GetPriceHistory(req.Symbol);
        var latest  = history[^1];

        return Ok(new
        {
            symbol        = latest.Symbol,
            price         = latest.Price,
            previousPrice = latest.PreviousPrice,
            changeAmount  = latest.ChangeAmount,
            changePercent = latest.ChangePercent,
            isUp          = latest.IsUp,
            recordedAt    = latest.RecordedAt
        });
    }

    // ── Queries ───────────────────────────────────────────────────────────────

    /// <summary>Returns all tracked symbols.</summary>
    [HttpGet("symbols")]
    public IActionResult GetSymbols()
        => Ok(market.GetTrackedSymbols());

    /// <summary>Returns the price history for a symbol.</summary>
    [HttpGet("{symbol}/history")]
    public IActionResult GetHistory(string symbol)
    {
        var history = market.GetPriceHistory(symbol);
        return Ok(history);
    }

    /// <summary>Returns all alerts generated by a specific observer type.</summary>
    [HttpGet("alerts/{observerType}")]
    public IActionResult GetAlerts(string observerType)
    {
        var observer = ResolveObserver(observerType);
        if (observer is null)
            return BadRequest(new { error = $"Unknown observer type '{observerType}'." });

        return Ok(observer.Alerts);
    }

    /// <summary>Returns alerts for all registered observers.</summary>
    [HttpGet("alerts")]
    public IActionResult GetAllAlerts()
    {
        var result = observers.Select(o => new
        {
            observer = o.Name,
            count    = o.Alerts.Count,
            alerts   = o.Alerts
        });

        return Ok(result);
    }

    // ── Helper ────────────────────────────────────────────────────────────────

    private IStockObserver? ResolveObserver(string type)
        => observers.FirstOrDefault(o =>
            o.Name.Equals(type, StringComparison.OrdinalIgnoreCase));
}
