using ObserverPattern.Api.Models;

namespace ObserverPattern.Api.Observers;

/// <summary>
/// Observer contract — every concrete observer implements this interface.
/// The subject calls <see cref="UpdateAsync"/> whenever a tracked price changes.
/// </summary>
public interface IStockObserver
{
    /// <summary>Unique name identifying the observer type.</summary>
    string Name { get; }

    /// <summary>Called by the subject when a stock price is updated.</summary>
    Task UpdateAsync(StockPrice price);

    /// <summary>All alerts generated by this observer so far.</summary>
    IReadOnlyList<StockAlert> Alerts { get; }
}
