### V1 — sadece Id ve Name
GET http://localhost:5155/api/v1/products
Accept: application/json

### V2 — Id, Name ve Price
GET http://localhost:5155/api/v2/products
Accept: application/json

### V2 only — tek ürün getir
GET http://localhost:5155/api/v2/products/1
Accept: application/json